<a href="https://colab.research.google.com/github/Alijgh003/d2l-exercises/blob/main/2.preliminaries/datamanipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
a = torch.arange(12 , dtype=torch.float32)

In [ ]:
a

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
b = a.numel()
b

12

In [ ]:
a.shape

torch.Size([12])

In [ ]:
a.reshape(3,4)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
xx = torch.randn(3,3,3)

In [ ]:
xx

tensor([[[-1.6392, -2.9405, -0.8742],
         [-1.1590, -0.2439,  0.9320],
         [ 0.3901,  1.9292,  1.1479]],

        [[-0.1119,  0.4554,  0.1127],
         [ 0.2474,  0.1454, -0.3639],
         [ 2.1808, -0.4764,  0.1420]],

        [[ 1.6254,  1.4768, -0.4031],
         [ 0.3653,  0.3485,  0.6039],
         [-0.3123, -2.4781,  0.5353]]])

In [ ]:
xx = torch.randn(4,4)
xx

tensor([[ 1.2855, -1.2426, -0.3519, -0.7168],
        [-0.3230,  0.4581, -0.9097, -0.2686],
        [-0.0559,  0.1690, -0.4626,  0.4679],
        [-0.1384,  1.3250,  1.3588,  0.0482]])

In [ ]:
xx[3,2]

tensor(1.3588)

In [ ]:
yy = torch.randn(4,4)

yy

tensor([[ 0.0938,  0.5293, -0.7047, -1.2604],
        [ 0.0306,  2.2500,  1.5359,  0.2834],
        [ 0.3271, -2.0599, -1.3924, -1.7307],
        [-0.8323, -0.3305,  0.9413,  1.3619]])

In [ ]:
uu = xx * yy
uu

tensor([[ 0.1206, -0.6577,  0.2480,  0.9034],
        [-0.0099,  1.0307, -1.3972, -0.0761],
        [-0.0183, -0.3482,  0.6441, -0.8098],
        [ 0.1152, -0.4379,  1.2790,  0.0657]])

In [ ]:
vv = xx + yy
vv

tensor([[ 1.3793, -0.7134, -1.0567, -1.9772],
        [-0.2923,  2.7081,  0.6262,  0.0148],
        [ 0.2712, -1.8909, -1.8550, -1.2627],
        [-0.9708,  0.9946,  2.3001,  1.4102]])

In [ ]:
torch.exp(xx)

tensor([[3.6165, 0.2886, 0.7033, 0.4883],
        [0.7240, 1.5810, 0.4026, 0.7644],
        [0.9456, 1.1842, 0.6297, 1.5967],
        [0.8707, 3.7624, 3.8917, 1.0494]])

In [ ]:
xx == yy

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
m = torch.arange(4,dtype=torch.float32).reshape(4,1)
n = torch.arange(3,dtype=torch.float32).reshape(1,3)
m,n

(tensor([[0.],
         [1.],
         [2.],
         [3.]]),
 tensor([[0., 1., 2.]]))

In [ ]:
m + n

tensor([[0., 1., 2.],
        [1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])

In [ ]:
m * n

tensor([[0., 0., 0.],
        [0., 1., 2.],
        [0., 2., 4.],
        [0., 3., 6.]])

In [ ]:
xx,  yy

(tensor([[ 1.2855, -1.2426, -0.3519, -0.7168],
         [-0.3230,  0.4581, -0.9097, -0.2686],
         [-0.0559,  0.1690, -0.4626,  0.4679],
         [-0.1384,  1.3250,  1.3588,  0.0482]]),
 tensor([[ 0.0938,  0.5293, -0.7047, -1.2604],
         [ 0.0306,  2.2500,  1.5359,  0.2834],
         [ 0.3271, -2.0599, -1.3924, -1.7307],
         [-0.8323, -0.3305,  0.9413,  1.3619]]))

In [ ]:
print(id(xx))
xx  += yy
print(id(xx))

138900875781008
138900875781008


In [ ]:
tensor1 = torch.arange(4,dtype=torch.float32).reshape(2,2)
tensor2 = torch.arange(4,dtype=torch.float32).reshape(2,2)
tensor1 , tensor2

(tensor([[0., 1.],
         [2., 3.]]),
 tensor([[0., 1.],
         [2., 3.]]))

In [ ]:
c = tensor1 * tensor2
c

tensor([[0., 1.],
        [4., 9.]])

In [ ]:
mat1 = torch.arange(3,dtype=torch.float32).reshape(3,1)
mat2 = torch.arange(3,dtype=torch.float32).reshape(1,3)

mat1, mat2


(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1., 2.]]))

In [ ]:
mat1 * mat2

tensor([[0., 0., 0.],
        [0., 1., 2.],
        [0., 2., 4.]])

In [ ]:
tensor1 >= tensor2

tensor([[True, True],
        [True, True]])

In [ ]:
tdt1 = torch.randn(2,2,2,dtype=torch.float32)
tdt2 = torch.randn(2,2,2,dtype=torch.float32)
tdt1 ,tdt2

(tensor([[[-0.1921, -1.0534],
          [ 0.5226, -1.8571]],
 
         [[-1.4225, -0.0814],
          [-1.0006,  1.0714]]]),
 tensor([[[-1.4865,  1.4554],
          [ 0.7032, -0.5707]],
 
         [[-1.3751,  1.2351],
          [-0.7391,  2.0406]]]))

In [ ]:
tdt3 = torch.randn(3,3,2,dtype=torch.float32)
tdt3

tensor([[[-0.0435,  0.9015],
         [-0.1902, -0.4000],
         [ 3.0277,  0.2325]],

        [[-1.6183, -0.7118],
         [ 1.5615, -1.6479],
         [-0.7424, -0.7296]],

        [[-1.2736,  0.3912],
         [-0.4234, -1.7102],
         [-0.4329,  1.5394]]])

In [ ]:
tdt3 + tdt2

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1